<?php
/**
 * Nome: turma.phtml
 * @author Lucas Filipe de Carvalho Cunha
 * Descricao: Página de listagem de turmas
 */
/* Monta a listagem de turmas  */
echo $this->listagemDisciplinas(); 
?>
<!--<section id="content_wrapper" style="margin-top: 50px;">
    <div id="content">
        <div class="mw1000 center-block">
            <div class="admin-form theme-primary">
                <blockquote class="blockquote-primary"><small>Cadastrar Curso</small></blockquote>
                <div id="" class="panel heading-border panel-primary">
                    <div class="panel-body bg-light">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Data de Criação</th>
                                    <th class="text-center">Criado Por</th>
                                    <th class="text-center hidden-xs">Nome</th>
                                    <th class="text-center">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-center">14</td>
                                    <td class="text-center">10/02/2014</td>
                                    <td class="text-center">ROBSON RODOVALHO</td>
                                    <td class="text-center hidden-xs">INSTITUTO DE VENCEDORES</td>
                                    <td class="text-center">
                                        <button type="button" onclick="" class="btn ladda-button btn-danger dark btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-times" aria-hidden="true"></i>                                    
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>   
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            Incluir Disciplinas
                                            <span class="ladda-spinner"></span>
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-center">14</td>
                                    <td class="text-center">10/02/2014</td>
                                    <td class="text-center">ROBSON RODOVALHO</td>
                                    <td class="text-center hidden-xs">INSTITUTO DE VENCEDORES</td>
                                    <td class="text-center">
                                        <button type="button" onclick="" class="btn ladda-button btn-danger dark btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-times" aria-hidden="true"></i>                                    
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>   
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            Incluir Disciplinas
                                            <span class="ladda-spinner"></span>
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-center">14</td>
                                    <td class="text-center">10/02/2014</td>
                                    <td class="text-center">ROBSON RODOVALHO</td>
                                    <td class="text-center hidden-xs">INSTITUTO DE VENCEDORES</td>
                                    <td class="text-center">
                                        <button type="button" onclick="" class="btn ladda-button btn-danger dark btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-times" aria-hidden="true"></i>                                    
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            <span class="ladda-label">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>   
                                            </span>
                                            <span class="ladda-spinner"></span>
                                        </button>
                                        <button type="button" onclick="" class="btn ladda-button btn-primary btn-xs mr5" data-style="zoom-in">
                                            Incluir Disciplinas
                                            <span class="ladda-spinner"></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="panel-footer">            
                        <div class="text-right">
                            <button type="button" onclick="" class="btn ladda-button btn-primary  mr10" data-style="zoom-in">
                                <span class="ladda-label">Cadastrar</span>
                                <span class="ladda-spinner"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>-->