<?php

use Application\Controller\Helper\Constantes;
use Application\Form\CelulaForm;
use Application\Form\EventoForm;
use Application\View\Helper\BotaoSimples;

/**
 * Nome: celula.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página de cadastro de célula
 */
$form = $this->Form;
$form->prepare();
$pagina = '';
$tituloDaPagina = '';
if ($form instanceof CelulaForm) {
    $tituloDaPagina = $this->translate(Constantes::$TRADUCAO_CADASTRO_CELULA) . ' <b class="text-danger">' . $this->translate(Constantes::$TRADUCAO_MULTIPLICACAO) . '</b>';
    $pagina = Constantes::$PAGINA_EVENTO_CELULA_PERSISTIR;
} else {
    if ($form instanceof EventoForm) {
        $tituloDaPagina = $this->translate(Constantes::$TRADUCAO_CADASTRO_CULTO);
        $pagina = Constantes::$PAGINA_EVENTO_CULTO_PERSISTIR;
    }
}

$actionUrl = $this->url(Constantes::$ROUTE_CADASTRO, array(Constantes::$PAGINA => $pagina));
$form->setAttribute(Constantes::$FORM_ACTION, $actionUrl);

echo $this->form()->openTag($form);
echo $this->formHidden($form->get(Constantes::$FORM_CSRF));
echo $this->formHidden($form->get(Constantes::$FORM_ID));
echo $this->templateFormularioTopo($tituloDaPagina);
?>
<div id="divFormulario">
    <!-- Inicio panel-body -->
    <div class="panel-body bg-light">
        <?php
        echo $this->divTempoRestante();
        echo $this->passoAPasso($form);
        echo $this->divMensagens();

        echo '<div id="divDiaDaSemanaHoraMinuto">';
        echo $this->inputDiaDaSemanaHoraMinuto($form);

        /* Botoes */
        $funcaoValidarDiaHoraEMinuto = $this->funcaoOnClick('validarDiaHoraEMinuto()');
        echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $funcaoValidarDiaHoraEMinuto);
        $funcaoVoltar = $this->funcaoOnClick('voltarListagemCultos()');
        if ($form instanceof CelulaForm) {
            $funcaoVoltar = $this->funcaoOnClick('voltarListagemCelulas()');
        }
        echo $this->botaoSimples(Constantes::$TRADUCAO_VOLTAR, $funcaoVoltar, 2);
        /* Fim Botoes */
        echo '</div>';

        echo '<div id="divExtras" class="hidden">';
        echo $this->inputExtras($form, $this->extra);
        $funcaoContinuar = '';
        if ($form instanceof EventoForm) {
            $funcaoContinuar = $this->funcaoOnClick('validarNome()');
        }
        if ($form instanceof CelulaForm) {
            $funcaoContinuar = $this->funcaoOnClick('validarDadosHospedeiro()');
        }
        echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $funcaoContinuar);
        $funcaoVoltar2 = $this->funcaoOnClick('voltarSelecionarDiaHoraEMinuto()');
        if ($form instanceof CelulaForm) {
            $funcaoVoltar2 = $this->funcaoOnClick('voltarEndereco()');
        }
        echo $this->botaoSimples(Constantes::$TRADUCAO_VOLTAR, $funcaoVoltar2, 2);
        echo '</div>';
        if ($form instanceof CelulaForm) {
            echo '</div>';
        }
        ?> 
        <div id="divConfirmacao" class="hidden">         
            <address>
                <div><strong><?php echo $this->translate(Constantes::$TRADUCAO_DIA_DA_SEMANA_SIMPLIFICADO) . ' / ' . $this->translate(Constantes::$TRADUCAO_HORA); ?></strong></div>
                <div><span id="spanDiaHora"></span></div>
            </address>
            <?php if ($form instanceof CelulaForm) { ?>
                <address>
                    <div><strong><?php echo $this->translate(Constantes::$TRADUCAO_HOSPEDEIRO); ?></strong></div>
                    <div><span id="spanNome"></span></div>
                    <div><span id="spanTelefone"></span></div>
                </address>                     
                <address>
                    <div><strong><?php echo $this->translate(Constantes::$TRADUCAO_ENDERECO); ?></strong></div>
                    <div><span id="spanLogradouroComplemento"></span></div>
                    <div><span id="spanEndereco"></span></div>                  
                </address>
                <?php
            } else {
                if ($form instanceof EventoForm) {
                    ?>
                    <address>
                        <div><strong>Nome</strong></div>
                        <div><span id="spanNome"></span></div>
                    </address>   
                    <address>
                        <div><strong>Equipe(s)</strong></div>
                        <div><span id="spanEquipes"></span></div>
                    </address>   
                    <?php
                }
            }

            $traducaoDoBotao = Constantes::$TRADUCAO_CADASTRAR;
            if (!empty($form->get(Constantes::$FORM_ID)->getValue())) {
                $traducaoDoBotao = Constantes::$TRADUCAO_ALTERAR;
            }
            $funcaoSubmeter = $this->funcaoOnClick('submeter(this.form)');
            echo $this->botaoSimples($traducaoDoBotao, $funcaoSubmeter, BotaoSimples::botaoSucesso);
            $funcaoVoltarNome = $this->funcaoOnClick('voltarPreencherNome()');
            echo $this->botaoSimples(Constantes::$TRADUCAO_VOLTAR, $funcaoVoltarNome, 2);
            ?>  
        </div>
    </div>
    <!-- Fim panel-body -->
    <!-- Inicio panel-footer -->
    <div class="hidden panel-footer text-right" style="height:65px;">
        <?php
        /* Botões */
        $labelVoltar = $this->translate(Constantes::$TRADUCAO_VOLTAR);
        $labelContinuar = $this->translate(Constantes::$TRADUCAO_CONTINUAR);
        $funcaoPreValidacao = '';
        $urlVoltar = '';
        if ($form instanceof CelulaForm) {
            $disabled = 'disabled';
            if (!empty($form->get(Constantes::$FORM_ID)->getValue())) {
                $disabled = '';
            }
            $funcaoPreValidacao = $this->funcaoOnClick(Constantes::$STRING_FUNCAO_PRE_VALIDACAO_CELULA) . ' ' . $disabled . ' id="botaoContinuar"';
            $urlVoltar = Constantes::$ROUTE_CADASTRO . Constantes::$PAGINA_CELULAS;
        } else {
            if ($form instanceof EventoForm) {
                $funcaoPreValidacao = $this->funcaoOnClick(Constantes::$STRING_FUNCAO_PRE_VALIDACAO_CULTO);
                $urlVoltar = Constantes::$ROUTE_CADASTRO . Constantes::$PAGINA_CULTOS;
            }
        }

        /* Voltar */
        echo $this->botaoLink($labelVoltar, $urlVoltar, 2, '');
        /* Continuar */
        echo $this->botaoLink($labelContinuar, Constantes::$STRING_HASHTAG, 0, $funcaoPreValidacao);
        ?>
    </div>
    <!-- Fim panel-footer -->
</div>
</div>
<?php
echo $this->templateFormularioRodape();
echo $this->form()->closeTag();

/* Layout com javascript para tela de cadastro de celula */
echo $this->layoutJSEventoValidacao;
