<?php

use Application\Controller\Helper\Constantes;
use Application\View\Helper\BotaoSimples;

$labelVoltar = $this->translate(Constantes::$TRADUCAO_VOLTAR);

$form = $this->Form;
$form->prepare();
$form->setAttribute(Constantes::$FORM_ACTION, Constantes::$ROUTE_CADASTRO . 'SolicitacaoFinalizar');
echo $this->form()->openTag($form);
echo $this->templateFormularioTopo($this->titulo);
?>
<div class="panel-body bg-light">
    <!--divSolicitacaoTipo-->
    <div id="divSolicitacaoTipo">
        <div class="section-divider mt20">
            <span>Selecione uma das opções abaixo</span>
        </div>
        Tipo de solicitação
        <select id="solicitacaoTipo" class="mt10 form-control" onchange="mostrarBotaoContinuar();">
            <option value="0">SELECIONE</option>
            <?php
            foreach ($this->solicitacaoTipos as $solicitacaoTipo) {
                echo '<option value="' . $solicitacaoTipo->getId() . '">' . $solicitacaoTipo->getNome() . '</option>';
            }
            ?>
        </select>
        <div id="divBotaoContinuarSelecionarTipo" class="hidden mt10">
            <?php
            echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $this->funcaoOnClick('selecionarTipo()'));
            ?>
        </div>
    </div>
    <!-- Progress Bar -->
    <div id="divProgress"  class="col-xs-12 hidden mt10 mb10">
        <div class="progress">
            <div id="divProgressBar" class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                0%
            </div>
        </div>
    </div>  
    <!--divObjetos-->
    <div id="divObjetos" class="hidden">
        <?php
        for ($indiceDeObejtos = 1; $indiceDeObejtos <= 3; $indiceDeObejtos++) {
            $funcaoOnclick = 'abrirSelecionarObjeto(' . $indiceDeObejtos . ', ' . $this->grupo->getId() . ')';
            $mostrarBotaoAdicionar = '';
            if ($indiceDeObejtos === 1) {
                $stringSelecioneOObjeto = 'Selecione o Lider que será transferido';
            }
            if ($indiceDeObejtos === 2) {
                $mostrarBotaoAdicionar = 'hidden';
                $stringSelecioneOObjeto = 'Selecione o Lider que receberá a transfêrencia';
            }
            if ($indiceDeObejtos === 3) {
                $mostrarBotaoAdicionar = 'hidden';
                $stringSelecioneOObjeto = 'Selecione os dados complementares';
            }
            ?>
            <!-- Bloco objeto -->
            <div id="blocoObjeto<?php echo $indiceDeObejtos; ?>" class="well col-xs-12 text-left" onClick='<?php // echo $funcaoOnclick;      ?>'>
                <div class="col-md-12">
                    <span id="spanSelecioneObjeto<?php echo $indiceDeObejtos; ?>"><?php echo $stringSelecioneOObjeto; ?></span>    
                    <span id="spanObjeto<?php echo $indiceDeObejtos; ?>"></span>
                    <span class="hidden" id="spanLoader<?php echo $indiceDeObejtos; ?>">Carregando <img src="/img/loader.gif" /></span>  
                </div>
                <div class="col-md-6">
                    <span id="spanFotos<?php echo $indiceDeObejtos; ?>"></span>
                </div>
                <div class="col-md-6">
                    <span class="quebraDeLinhaDeSpan" id="spanNomeLideres<?php echo $indiceDeObejtos; ?>"></span>
                    <span class="quebraDeLinhaDeSpan" id="spanCelulaQuantidade<?php echo $indiceDeObejtos; ?>"></span>
                    <span class="quebraDeLinhaDeSpan" id="spanQuantidadeLideres<?php echo $indiceDeObejtos; ?>"></span>
                </div>
                <div id="divBotaoSelecionar<?php echo $indiceDeObejtos; ?>" class="<?php echo $mostrarBotaoAdicionar ?>">
                    <?php
                    echo $this->botaoSimples(Constantes::$TRADUCAO_SELECIONAR, $this->funcaoOnClick($funcaoOnclick), BotaoSimples::botaoPequenoImportante);
                    ?>
                </div>
                <div id="divBotaoLimpar<?php echo $indiceDeObejtos; ?>" class="hidden">
                    <button type="button" onClick='limparObjeto(<?php echo $indiceDeObejtos; ?>);' style="float: right;" onclick='location.href = "#";' class="btn ladda-button btn-default dark btn-xs mr5" data-style="zoom-in">
                        <span class="ladda-label">Limpar</span>
                    </button>
                </div>
                <div id="divCheckDadosInseridos<?php echo $indiceDeObejtos; ?>" class="checkDadosInseridos hidden">
                    <span class="glyphicon glyphicon-ok text-success"></span>
                </div>
            </div>
            <?php
        }
        ?>
    </div>
    <!--divSelecionarLider-->
    <div id="divSelecionarLider" class="hidden">
        <div id="treeLideres" class="fancytree-radio">
            <ul id="treeData" style="display: none;">
                <?php echo $this->listagemLideresTransferencia($this->discipulos); ?>
            </ul>
        </div>
    </div> 
    <!--divSelecionarNumeracao-->
    <div id="divSelecionarNumeracao" class="hidden">
        <div class="section-divider mt20">
            <span>Selecione uma numeração</span>
        </div>
        <select id="numero" class="mt10 form-control">
            <option value="0">SELECIONE</option>
            <?php
            for ($indiceNumeracao = 1; $indiceNumeracao <= 24; $indiceNumeracao++) {
                echo "<option value='$indiceNumeracao'>$indiceNumeracao</option>";
            }
            ?>
        </select>
        <button type="button" onClick='selecionarNumeracao()' style="float: right;" class="mt10 btn ladda-button btn-primary mr5" data-style="zoom-in">
            <span class="ladda-label">Selecionar</span>
        </button>
    </div>
    <!--divBotaoContinuar-->
    <div id="divBotaoContinuar" class="hidden">
        <?php
        echo $this->botaoSimples(Constantes::$TRADUCAO_CONTINUAR, $this->funcaoOnClick('continuarParaConfimacao()'), BotaoSimples::botaoSucesso);
        ?>
    </div>
    <!--divTelaConfirmacao-->
    <div id="divTelaConfirmacao" class="hidden">
        <div class="panel heading-border panel-info">
            <div class="panel-body">
                <address>
                    tem isso
                    va acontecer isso
                </address>                                  
            </div>                 
        </div>
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="section text-center">
                    <label class="option block mt15">
                        <input type="checkbox" name="checked" value="checked" onclick="pedirSenha();">
                        <span class="checkbox"></span>
                        Confirmo isso
                    </label> 
                </div>
            </div>
        </div>
        <?php
        $stringNomeDaFuncaoOnClickVoltar = 'voltaAosObjetos()';
        echo $this->botaoSimples($labelVoltar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltar), BotaoSimples::botaoMenorImportancia);
        ?>
    </div>
    <!--divSenha-->
    <div id="divSenha" class="hidden">
        <div class="">
            <div class="section-divider"> 
                <span>Confirma essa solicitação?</span>
            </div>
            <?php echo $this->divMensagens(); ?>
            <div class="row">
                <div class="col-sm-12 col-xs-12">
                    <div class="section text-center">
                        <input id="senha" type="password" class="gui-input" placeholder="<?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?>" />
                    </div>
                </div>
            </div>
        </div>
        <div class="text-right" style="height:65px;">
            <?php
            /* Botões */
            $labelConfirmar = $this->translate(Constantes::$TRADUCAO_CONFIRMACAO);
            $stringNomeDaFuncaoOnClickVoltarConfirmacao = 'continuarParaConfimacao()';
            $stringNomeDaFuncaoOnClickConfimarSolicitacao = 'validarSenha(this.form)';
            echo $this->botaoSimples($labelConfirmar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickConfimarSolicitacao), BotaoSimples::botaoPerigoso);
            echo $this->botaoSimples($labelVoltar, $this->funcaoOnClick($stringNomeDaFuncaoOnClickVoltarConfirmacao), BotaoSimples::botaoMenorImportancia);
            ?>      
        </div>    
    </div>
</div>
<?php
echo $this->formHidden($form->get('solicitacaoTipoId'));
echo $this->formHidden($form->get('objeto1'));
echo $this->formHidden($form->get('objeto2'));
echo $this->formHidden($form->get('numeracao'));
echo $this->form()->closeTag();
