<?php

use Application\Controller\Helper\Constantes;
use Application\Model\Entity\SolicitacaoTipo;

$html = '';
$html .= $this->templateFormularioTopo($this->titulo);
$html .= '<div class="panel-body bg-light">';
if ($this->solicitacoes) {
    $html .= '<table class="table">';

    $html .= '<thead>';

    $html .= '<tr>';
    $html .= '<th class="hidden-xs">Tipo</th>';
    $html .= '<th class="hidden-xs">Solicitado em</th>';
    $html .= '<th class="hidden-xs">Por</th>';
    $html .= '<th>O que ou quem?</th>';
    $html .= '<th>Para</th>';
    $html .= '<th>Status</th>';
    $html .= '</tr>';

    $html .= '</thead>';

    $html .= '<tbody>';

    foreach ($this->solicitacoes as $solicitacao) {
        $html .= '<tr>';
        $html .= '<td class="hidden-xs">' . $solicitacao->getSolicitacaoTipo()->getNome() . '</td>';
        $html .= '<td class="hidden-xs">' . $solicitacao->getData_criacaoStringPadraoBrasil() . '</td>';
        $html .= '<td class="hidden-xs">' . $solicitacao->getPessoa()->getNomePrimeiroUltimo() . '</td>';

        if ($solicitacao->getSolicitacaoTipo()->getId() === SolicitacaoTipo::TRANSFERIR_LIDER_NA_PROPRIA_EQUIPE) {
            for ($indice = 1; $indice <= 2; $indice++) {
                $html .= '<td>';
                if ($indice === 1) {
                    $objeto = $solicitacao->getObjeto1();
                }
                if ($indice === 2) {
                    $objeto = $solicitacao->getObjeto2();
                }
                $grupo = $this->repositorio->getGrupoORM()->encontrarPorId($objeto);
                $html .= $grupo->getNomeLideresAtivos();
                $html .= '</td>';
            }
        }
        if ($solicitacao->getSolicitacaoSituacaoAtiva()) {
            $html .= '<td>' . $solicitacao->getSolicitacaoSituacaoAtiva()->getSituacao()->getNome() . '</td>';
        }
        $html .= '</tr>';
    }

    $html .= '</tbody>';

    $html .= '</table>';
} else {
    $html .= '<div class="alert alert-warning"><i class="fa fa-warning pr10" aria-hidden="true"></i>&nbsp;Sem solicitações!</div>';
}
$html .= '</div>';

$html .= '<div class="panel-footer text-right">';
$stringNomeDaFuncaoOnClickCadastro = 'funcaoCircuito("cadastroSolicitacao", 0)';
$html .= $this->botaoLink($this->translate(Constantes::$TRADUCAO_CADASTRAR), Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickCadastro));
$html .= '</div>';

$html .= $this->templateFormularioRodape();
echo $html;

