<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pessoa extends \Application\Model\Entity\Pessoa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inputFilter', 'inputFilterCadastrarPonteProspecto', 'grupoResponsavel', 'eventoFrequencia', 'grupoPessoa', 'pessoaHierarquia', 'tarefa', 'ponteProspectoProspectos', 'ponteProspectoPonte', 'nome', 'telefone', 'email', 'senha', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'inputFilter', 'inputFilterCadastrarPonteProspecto', 'grupoResponsavel', 'eventoFrequencia', 'grupoPessoa', 'pessoaHierarquia', 'tarefa', 'ponteProspectoProspectos', 'ponteProspectoPonte', 'nome', 'telefone', 'email', 'senha', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pessoa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data, $nomeFromulario = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data, $nomeFromulario));

        return parent::exchangeArray($data, $nomeFromulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilterCadastrarPonteProspecto($nomeFormulario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilterCadastrarPonteProspecto', array($nomeFormulario));

        return parent::getInputFilterCadastrarPonteProspecto($nomeFormulario);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsabilidadesAtivas($todasResposabilidades = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsabilidadesAtivas', array($todasResposabilidades));

        return parent::getResponsabilidadesAtivas($todasResposabilidades);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiroUltimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiroUltimo', array());

        return parent::getNomePrimeiroUltimo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiro', array());

        return parent::getNomePrimeiro();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomePrimeiroPrimeiraSiglaUltimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomePrimeiroPrimeiraSiglaUltimo', array());

        return parent::getNomePrimeiroPrimeiraSiglaUltimo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequenciasFiltradosPorEvento($idEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequenciasFiltradosPorEvento', array($idEvento));

        return parent::getEventoFrequenciasFiltradosPorEvento($idEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequenciaFiltradoPorEventoEDia($idEvento, $diaRealDoEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequenciaFiltradoPorEventoEDia', array($idEvento, $diaRealDoEvento));

        return parent::getEventoFrequenciaFiltradoPorEventoEDia($idEvento, $diaRealDoEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeTemAlgumaResponsabilidadeAtiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeTemAlgumaResponsabilidadeAtiva', array());

        return parent::verificarSeTemAlgumaResponsabilidadeAtiva();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_nascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_nascimento', array());

        return parent::getData_nascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_nascimentoFormatada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_nascimentoFormatada', array());

        return parent::getData_nascimentoFormatada();
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumento', array());

        return parent::getDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha, $adicionarMD5 = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha, $adicionarMD5));

        return parent::setSenha($senha, $adicionarMD5);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_nascimento($data_nascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_nascimento', array($data_nascimento));

        return parent::setData_nascimento($data_nascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumento($documento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumento', array($documento));

        return parent::setDocumento($documento);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', array());

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', array($token));

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function gerarToken($tipo = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gerarToken', array($tipo));

        return parent::gerarToken($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data', array());

        return parent::getToken_data();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_ano()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_ano', array());

        return parent::getToken_data_ano();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_mes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_mes', array());

        return parent::getToken_data_mes();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_data_dia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_data_dia', array());

        return parent::getToken_data_dia();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken_data($token_data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken_data', array($token_data));

        return parent::setToken_data($token_data);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora', array());

        return parent::getToken_hora();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_hora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_hora', array());

        return parent::getToken_hora_hora();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_minutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_minutos', array());

        return parent::getToken_hora_minutos();
    }

    /**
     * {@inheritDoc}
     */
    public function getToken_hora_segundos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken_hora_segundos', array());

        return parent::getToken_hora_segundos();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken_hora($token_hora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken_hora', array($token_hora));

        return parent::setToken_hora($token_hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavel', array());

        return parent::getGrupoResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoResponsavel($grupoResponsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoResponsavel', array($grupoResponsavel));

        return parent::setGrupoResponsavel($grupoResponsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($telefone));

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoFrequencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoFrequencia', array());

        return parent::getEventoFrequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoFrequencia($eventoFrequencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoFrequencia', array($eventoFrequencia));

        return parent::setEventoFrequencia($eventoFrequencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGrupoPessoa', array());

        return parent::getIdGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGrupoPessoa($idGrupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGrupoPessoa', array($idGrupoPessoa));

        return parent::setIdGrupoPessoa($idGrupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaHierarquiaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaHierarquiaAtivo', array());

        return parent::getPessoaHierarquiaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoaAtivo', array());

        return parent::getGrupoPessoaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoa', array());

        return parent::getGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPessoa($grupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPessoa', array($grupoPessoa));

        return parent::setGrupoPessoa($grupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilterPessoaFrequencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilterPessoaFrequencia', array());

        return parent::getInputFilterPessoaFrequencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaHierarquia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaHierarquia', array());

        return parent::getPessoaHierarquia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaHierarquia($pessoaHierarquia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaHierarquia', array($pessoaHierarquia));

        return parent::setPessoaHierarquia($pessoaHierarquia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarefa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarefa', array());

        return parent::getTarefa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarefa($tarefa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarefa', array($tarefa));

        return parent::setTarefa($tarefa);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao($date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array($date));

        return parent::setDataEHoraDeCriacao($date);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoFormatada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoFormatada', array());

        return parent::getData_criacaoFormatada();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoFormatoBandoDeDados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoFormatoBandoDeDados', array());

        return parent::getData_criacaoFormatoBandoDeDados();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

}
