<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grupo extends \Application\Model\Entity\Grupo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'grupoResponsavel', 'grupoEvento', 'grupoPessoa', 'grupoPaiFilhoFilhos', 'grupoPaiFilhoPai', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
        }

        return array('__isInitialized__', 'grupoResponsavel', 'grupoEvento', 'grupoPessoa', 'grupoPaiFilhoFilhos', 'grupoPaiFilhoPai', 'id', 'data_criacao', 'hora_criacao', 'data_inativacao', 'hora_inativacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Grupo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavel', array());

        return parent::getGrupoResponsavel();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoResponsavelAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoResponsavelAtivo', array());

        return parent::getGrupoResponsavelAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhosAtivos($periodo = -1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhosAtivos', array($periodo));

        return parent::getGrupoPaiFilhoFilhosAtivos($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhosPorMes($mes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhosPorMes', array($mes));

        return parent::getGrupoPaiFilhoFilhosPorMes($mes);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhosAtivosReal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhosAtivosReal', array());

        return parent::getGrupoPaiFilhoFilhosAtivosReal();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoPaiAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoPaiAtivo', array());

        return parent::getGrupoPaiFilhoPaiAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeLideresAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeLideresAtivos', array());

        return parent::getNomeLideresAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoResponsavel($grupoResponsavel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoResponsavel', array($grupoResponsavel));

        return parent::setGrupoResponsavel($grupoResponsavel);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEvento', array());

        return parent::getGrupoEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoAcima()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoAcima', array());

        return parent::getGrupoEventoAcima();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoEventoAtivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoEventoAtivos', array());

        return parent::getGrupoEventoAtivos();
    }

    /**
     * {@inheritDoc}
     */
    public function verificaSeParticipaDoEvento($idEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificaSeParticipaDoEvento', array($idEvento));

        return parent::verificaSeParticipaDoEvento($idEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoasNoPeriodo($periodo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoasNoPeriodo', array($periodo));

        return parent::getGrupoPessoasNoPeriodo($periodo);
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoEvento($grupoEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoEvento', array($grupoEvento));

        return parent::setGrupoEvento($grupoEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoa', array());

        return parent::getGrupoPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPessoaAtivasNoPeriodoDe1Semanas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPessoaAtivasNoPeriodoDe1Semanas', array());

        return parent::getGrupoPessoaAtivasNoPeriodoDe1Semanas();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPessoa($grupoPessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPessoa', array($grupoPessoa));

        return parent::setGrupoPessoa($grupoPessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', array());

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventos($eventos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventos', array($eventos));

        return parent::setEventos($eventos);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoFilhos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoFilhos', array());

        return parent::getGrupoPaiFilhoFilhos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPaiFilhoFilhos($grupoPaiFilhoFilhos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPaiFilhoFilhos', array($grupoPaiFilhoFilhos));

        return parent::setGrupoPaiFilhoFilhos($grupoPaiFilhoFilhos);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoPaiFilhoPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoPaiFilhoPai', array());

        return parent::getGrupoPaiFilhoPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoPaiFilhoPai($grupoPaiFilhoPai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoPaiFilhoPai', array($grupoPaiFilhoPai));

        return parent::setGrupoPaiFilhoPai($grupoPaiFilhoPai);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeCriacao($date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeCriacao', array($date));

        return parent::setDataEHoraDeCriacao($date);
    }

    /**
     * {@inheritDoc}
     */
    public function verificarSeEstaAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verificarSeEstaAtivo', array());

        return parent::verificarSeEstaAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEHoraDeInativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEHoraDeInativacao', array());

        return parent::setDataEHoraDeInativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function gerarToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gerarToken', array());

        return parent::gerarToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacao', array());

        return parent::getData_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoFormatada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoFormatada', array());

        return parent::getData_criacaoFormatada();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_criacaoFormatoBandoDeDados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_criacaoFormatoBandoDeDados', array());

        return parent::getData_criacaoFormatoBandoDeDados();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_criacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_criacao', array());

        return parent::getHora_criacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getData_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData_inativacao', array());

        return parent::getData_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHora_inativacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora_inativacao', array());

        return parent::getHora_inativacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_criacao($data_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_criacao', array($data_criacao));

        return parent::setData_criacao($data_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_criacao($hora_criacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_criacao', array($hora_criacao));

        return parent::setHora_criacao($hora_criacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setData_inativacao($data_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData_inativacao', array($data_inativacao));

        return parent::setData_inativacao($data_inativacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setHora_inativacao($hora_inativacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora_inativacao', array($hora_inativacao));

        return parent::setHora_inativacao($hora_inativacao);
    }

}
