<?php

use Application\Controller\Helper\Constantes;
use Application\Controller\Helper\Funcoes;

$cursoRecebida = $this->curso;

$tituloDaPagina = $this->translate(Constantes::$TRADUCAO_CONFIRMACAO_EXCLUSAO);
echo $this->templateFormularioTopo($tituloDaPagina, Constantes::$STRING_DIV_CONFIRMACAO);
?>
<div class="panel-body bg-light">
    <div class="section-divider">
        <span>
            <?php
            echo $this->translate(Constantes::$TRADUCAO_PERGUNTA_EXCLUSAO_CURSO);
            ?>
        </span>
    </div>
    <div class="panel heading-border panel-danger">
        <div class="panel-body"> 


            <address>
                <div><strong><?php echo $this->translate(Constantes::$TRADUCAO_NOME); ?></strong></div>
                <div><?php echo $cursoRecebida->getNome(); ?></div>
            </address>
            <address>
                <div><strong><?php echo "Data de Criação:" ?></strong></div>
                <div><?php echo $cursoRecebida->getData_criacaoStringPadraoBrasil(); ?></div>
            </address>
            <address>
                <div><strong><?php echo "Criado Por:" ?></strong></div>
                <div><?php echo $cursoRecebida->getPessoa()->getNomePrimeiroPrimeiraSiglaUltimo(); ?></div>
            </address>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            <div class="section text-center">
                <label class="option block mt15">
                    <input type="checkbox" name="checked" value="checked" onclick="mostrarMotivos();">
                    <span class="checkbox"></span>
                    <?php
                    echo $this->translate(Constantes::$TRADUCAO_CIENCIA_EXCLUSAO_CURSO);
                    ?>
                </label>
            </div>
        </div>
    </div>
    <div id="divMotivo" class="panel heading-border panel-danger hidden">

        <div class="panel-footer text-right" style="height:65px;">
<?php
$labelVoltar = $this->translate(Constantes::$TRADUCAO_VOLTAR);
/* Botões */
$urlVoltar = Constantes::$ROUTE_CURSO;
$urlVoltar .= Constantes::$PAGINA_CURSO_LISTAR;

$labelContinuar = $this->translate(Constantes::$TRADUCAO_CONTINUAR);
$stringNomeDaFuncaoOnClickContinuarExclusao = '$("#divConfirmacao").toggleClass("' . Constantes::$FORM_HIDDEN . '");' .
        '$("#divSenha").toggleClass("' . Constantes::$FORM_HIDDEN . '")';

echo $this->botaoLink($labelVoltar, $urlVoltar, 2, '');
echo $this->botaoLink($labelContinuar, Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickContinuarExclusao));
?>
        </div>
    </div>
    <div id="divBotaoVoltar" class="panel-footer text-right" style="height:65px;">
<?php
echo $this->botaoLink($labelVoltar, $urlVoltar, 2, '');
?>
    </div>
</div>
</div>
<div id="divSenha" class="panel heading-border panel-danger hidden">
    <div class="panel-body bg-light">
        <div class="section-divider">
            <span><?php echo $this->translate(Constantes::$TRADUCAO_DIGITE_SENHA_EXCUSAO_SENHA); ?></span>
        </div>
<?php echo $this->divMensagens(); ?>
        <div class="row">
            <div class="col-sm-12 col-xs-12">
                <div class="section text-center">
                    <input id="senha" type="password" class="gui-input" placeholder="<?php echo $this->translate(Constantes::$TRADUCAO_SENHA); ?>" />
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer text-right" style="height:65px;">
<?php
/* Botões */
$labelConfirmar = $this->translate(Constantes::$TRADUCAO_CONFIRMACAO);
$stringNomeDaFuncaoOnClickConfimarExclusao = 'validarExclusao(' . $curso->getId() . ')';

echo $this->botaoLink($labelVoltar, Constantes::$STRING_HASHTAG, 2, $this->funcaoOnClick($stringNomeDaFuncaoOnClickContinuarExclusao));
echo $this->botaoLink($labelConfirmar, Constantes::$STRING_HASHTAG, 0, $this->funcaoOnClick($stringNomeDaFuncaoOnClickConfimarExclusao));
?>
    </div>
        <?php
        echo $this->templateFormularioRodape();
