<?php

use Application\Form\KleoForm;
use Application\Controller\KleoController;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'admAtivoFinalizar');
$formulario->setAttribute(KleoForm::stringId, 'form');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
?>
<!-- Panel Wizard Form Container -->
<div class="panel" id="panelWizard">
  <div class="panel-heading">
    <h3 class="panel-title">Novo Ativo</h3>
  </div>
  <div class="panel-body">
    <!-- Steps -->
    <div class="pearls row">
      <div id="passo1" class="pearl current col-6">
        <div class="pearl-icon"><i class="icon wb-user" aria-hidden="true"></i></div>
        <span class="pearl-title">Dados Pessoais</span>
      </div>
      <div id="passo2" class="pearl col-6">
        <div class="pearl-icon"><i class="icon wb-envelope" aria-hidden="true"></i></div>
        <span class="pearl-title">Email</span>
      </div>
    </div>
    <!-- End Steps -->

    <!-- Wizard Content -->
    <form id="exampleFormContainer">
      <div class="wizard-content">
        <div class="wizard-pane active" id="exampleAccountOne" role="tabpanel">
          <?php
          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoNomeCompleto, $formulario->get(KleoForm::inputNome));
          echo '</div>';

          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoDocumento, $formulario->get(KleoForm::inputDocumento));
          echo '</div>';

          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoDia, $formulario->get(KleoForm::inputDia),4);
          echo $this->inputFormulario(KleoForm::traducaoMes, $formulario->get(KleoForm::inputMes),4);
          echo $this->inputFormulario(KleoForm::traducaoAno, $formulario->get(KleoForm::inputAno),4);
          echo '</div>';

          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoSexo, $formulario->get(KleoForm::inputSexo));
          echo '</div>';
          ?>
        </div>
        <div class="wizard-pane" id="exampleBillingOne" role="tabpanel">
          <?php
          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoEmail, $formulario->get(KleoForm::inputEmail));
          echo '</div>';
          echo '<div class="row">';
          echo $this->inputFormulario(KleoForm::traducaoRepetirEmail, $formulario->get(KleoForm::inputRepetirEmail));
          echo '</div>';
          ?>
        </div>
      </div>
    </form>
    <!-- Wizard Content -->
  </div>
</div>
<!-- End Panel Wizard Form Container -->
<?php
echo $this->form()->closeTag();
