<?php
use Application\Controller\KleoController;
?>
<?php if(count($this->pontes) == 0 && $this->token == 0){ ?>
<div class="alert alert-icon alert-info w-full" role="alert">
  <i class="icon wb-alert" aria-hidden="true"></i>
  <p>Vamos começar cadastrando uma Ponte.</p>
</div>
<?php } ?>
<!-- Panel -->
<div class="panel">
  <div class="panel-heading">
    <h2 class="panel-title bg-blue-600 white">
      <?php 
      echo KleoController::diaDaSemanaPorDia(date('N'),1).'<br />';
      echo KleoController::mesPorExtenso(date('m'),1).' '. date('d'); ?>
      <p>
        <?php
        echo $this->cabecalhoDePeriodos();
        ?>
      </p>
    </h2>
  </div>
  <div class="panel-body">
    <?php echo $this->agenda(); ?>
  </div>
</div>
<?php 
echo $this->cadastroDePonteEProspecto();
