<?php
use Application\Controller\KleoController;
echo $this->performancePontes();
?>
<!-- Panel -->
<div class="panel">
  <div class="panel-heading">
    <h2 class="panel-title bg-blue-600 white">
      <?php 
      echo KleoController::diaDaSemanaPorDia(date('N'),1).'<br />';
      echo KleoController::mesPorExtenso(date('m'),1).' '. date('d'); ?>
      <p>
        <?php
        echo $this->cabecalhoDePeriodos();
        ?>
      </p>
    </h2>
  </div>
  <div class="panel-body">
    <?php echo $this->agenda(); ?>
  </div>
</div>
<?php 
echo $this->cadastroDePonteEProspecto();
