<?php

use Application\Model\Entity\TarefaTipo;
use Application\Model\Entity\Tarefa;
use Application\Model\Entity\Evento;
use Application\Model\Entity\GrupoPessoaTipo;
use Application\Model\Entity\FatoCiclo;
use Application\Form\KleoForm;
use Application\Controller\KleoController;
use Application\View\Helper\Botao;
?>
<?php if(count($this->pontes) == 0){ ?>
<div class="alert alert-icon alert-info w-full" role="alert">
  <i class="icon wb-alert" aria-hidden="true"></i>
  <p>Vamos começar cadastrando uma Ponte.</p>
</div>
<?php } ?>
<!-- Panel -->
<div class="panel">
  <div class="panel-heading">
    <h2 class="panel-title bg-blue-600 white">
      <?php 
      echo KleoController::diaDaSemanaPorDia(date('N'),1).'<br />';
      echo KleoController::mesPorExtenso(date('m'),1).' '. date('d'); ?>
      <p>
        <?php
        if($this->token != -1){
          echo '<a class="btn btn-success btn-sm" href="/adm/-1"> << Ciclo Anterior</a>&nbsp;';
        }
        if($this->token != 0){
          echo '<a class="btn btn-success btn-sm" href="/adm">Ciclo Atual</a>&nbsp;';
        }
        if($this->token != 1){
          echo '<a class="btn btn-success btn-sm" href="/adm/1"> >> Ciclo A frente</a>';
        }
        ?>
      </p>
    </h2>
  </div>
  <div class="panel-body">
    <table class='table table-sm'>
      <tbody>
        <?php 
        $ocorreuEvento = false;
        for($indiceDias = $this->inicioDoCiclo;$indiceDias <= $this->fimDoCiclo;$indiceDias++){
          if(date('d', strtotime('now +'.$indiceDias.' days')) == 1){
            echo '<tr class="bg-primary text-center"><td colspan="2"><p>'.KleoController::mesPorExtenso(date('m', strtotime('now +'.$indiceDias.' days')),1).'</p></td></tr>';       
          }

          $idAncora = '';
          if($indiceDias === 0){
            $idAncora = 'ancora';
          }
        ?>
        <tr id="<?php echo $idAncora; ?>">
          <td>
            <p>
              <?php 
          echo KleoController::diaDaSemanaPorDia(date('N', strtotime('now +'.$indiceDias.' days'))); 
          echo '<br />' . date('d', strtotime('now +'.$indiceDias.' days')); 
              ?>
            </p>
          </td>
          <td>
            <?php
          if($this->agenda[$indiceDias][0] instanceof Tarefa || $this->agenda[$indiceDias][0] instanceof Evento){
            foreach($this->agenda[$indiceDias] as $elemento){
              if($elemento instanceof Tarefa){
                if($elemento->getTarefaTipo()->getId() === TarefaTipo::LIGAR){
                  $corTarefa = 'info';
                  $icone = 'fa-phone';
                }
                if($elemento->getTarefaTipo()->getId() === TarefaTipo::MENSAGEM){
                  $corTarefa = 'success';
                  $icone = 'fa-envelope';
                }
                $iconeTarefaRealizada = 'down';
                $corTarefaRealizada = 'default';
                if($elemento->getRealizada() === "S"){
                  $iconeTarefaRealizada = 'up';
                  $corTarefaRealizada = 'primary';
                }
            ?>
            <div class="row px-10">
              <div class="alert alert-icon alert-<?php echo $corTarefa; ?> w-full" role="alert">
                <i class="icon <?php echo $icone; ?>" aria-hidden="true"></i>
                <?php 
                echo $elemento->getTarefaTipo()->getNome() . ' para ' . $elemento->getPessoa()->getNome(); 
                if(count($elemento->getPessoa()->getPonteProspectoPonte())>0){
                  echo ' prospecto de '.$elemento->getPessoa()->getPonteProspectoPonte()[0]->getPonteProspectoPonte()->getNome();
                }
                if($elemento->getTarefaTipo()->getId() === TarefaTipo::LIGAR){
                  echo '<p><button class="btn btn-primary btn-sm" onclick="clicarAcao('.FatoCiclo::CLIQUE_LIGACAO.', \''.$elemento->getPessoa()->getTelefone().'\', 0);" >'.$elemento->getPessoa()->getTelefone().'</button>';
                }
                if($elemento->getTarefaTipo()->getId() === TarefaTipo::MENSAGEM){
                  echo '<p><button class="btn btn-primary btn-sm"  onclick="clicarAcao('.FatoCiclo::CLIQUE_MENSAGEM.', \''.$elemento->getPessoa()->getTelefone().'\', \''.$elemento->getPessoa()->getNome().'\');">MSG Whats</button>';
                } 
                ?>
                <button id="botao_<?php echo $elemento->getId(); ?>" 
                        onclick="mudarFrequencia(1, <?php echo $elemento->getId(); ?>,0,0,0);" 
                        type="button" class="float-right btn btn-sm btn-<?php echo $corTarefaRealizada; ?>" >
                  <i class="icon fa-thumbs-<?php echo $iconeTarefaRealizada; ?>" aria-hidden="true"></i>
                </button>
                </p>
            </div>
      </div>
        <?php
              }
              if($elemento instanceof Evento){
                $ocorreuEvento = true;
        ?>
        <div class="row px-10">
          <div class="alert alert-danger w-full" role="alert">
            <?php 
                echo $elemento->getNome(); 
                if($this->grupoPessoas){
                  foreach($this->grupoPessoas as $grupoPessoa){
                    $mostrar = true;
                    $diaRealDoEvento = date('Y-m-d', strtotime('now +'.$indiceDias.' days'));
                    if($grupoPessoa->getData_criacaoFormatoBandoDeDados() >= $diaRealDoEvento){
                      $mostrar = false;
                    }                    
                    if($mostrar){
                      echo '<p>'.$grupoPessoa->getPessoa()->getNome();
                      if(count($grupoPessoa->getPessoa()->getPonteProspectoPonte())>0){
                        echo ' prospecto de '.$grupoPessoa->getPessoa()->getPonteProspectoPonte()[0]->getPonteProspectoPonte()->getNome();
                      }

                      $eventosFiltrado = $grupoPessoa->getPessoa()->getEventoFrequenciaFiltradoPorEventoEDia($elemento->getId(), $diaRealDoEvento);
                      $iconeTarefaRealizada = 'down';
                      $corTarefaRealizada = 'default';
                      if($eventosFiltrado){
                        if($eventosFiltrado->getFrequencia() === "S"){
                          $iconeTarefaRealizada = 'up';
                          $corTarefaRealizada = 'primary';
                        }  
                      }

            ?>
            <button id="botao_<?php echo $elemento->getId().'_'.$grupoPessoa->getPessoa()->getId(); ?>" 
                    onclick="mudarFrequencia(2,0, <?php echo $elemento->getId() . ',' . $grupoPessoa->getPessoa()->getId() . ', \'' .  $diaRealDoEvento . '\'' ?>);"
                    type="button" class="float-right btn btn-sm btn-<?php echo $corTarefaRealizada; ?>" >
              <i class="icon fa-thumbs-<?php echo $iconeTarefaRealizada; ?>" aria-hidden="true"></i>
            </button>
            <?php
                      echo '</p>';
                    }

                  }
                }
            ?>
          </div>
        </div>
        <?php
              }
            }
            /* fim foreach */
          }else{
            echo $this->agenda[$indiceDias][0];
          }
        ?>
      </td>
    </tr>
  <?php 
          if($ocorreuEvento){
            break;
          }
        } 
  ?>
  </tbody>
</table>
</div>
</div>
<!-- Site Action -->
<?php if($this->token == 0){ ?>
<div id="divSiteAction" class="site-action" data-plugin="actionBtn">
  <button onclick="$('#divSiteAction').toggleClass('active');" type="button" class="site-action-toggle btn-raised btn btn-success btn-floating">
    <i class="front-icon wb-plus animation-scale-up" aria-hidden="true"></i>
    <i class="back-icon wb-close animation-scale-up" aria-hidden="true"></i>
  </button>
  <div class="site-action-buttons">
    <?php if(count($this->pontes) < 2){ ?>
    <button onclick="selecionarPonteProspecto(<?php echo GrupoPessoaTipo::PONTE; ?>);" type="button" data-toggle="modal" data-target="#addStageFrom" class="btn-raised btn btn-success btn-floating animation-slide-bottom">
      <i class="icon wb-user" aria-hidden="true"></i>
    </button>
    <?php } ?>
    <?php if(count($this->pontes) > 0){ ?>
    <button onclick="selecionarPonteProspecto(<?php echo GrupoPessoaTipo::PROSPECTO; ?>);" type="button" data-toggle="modal" data-target="#addStageFrom" class="btn-raised btn btn-success btn-floating animation-slide-bottom">
      <i class="icon wb-users" aria-hidden="true"></i>
    </button>
    <?php } ?>
  </div>
</div>
<?php } ?>
<!-- End Site Action -->
<?php
?>
<div class="modal fade" id="addStageFrom" aria-hidden="true" aria-labelledby="addStageFrom"
     role="dialog" tabindex="-1">
  <div class="modal-dialog modal-simple">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" aria-hidden="true" data-dismiss="modal">×</button>
        <h4 id="modalTitle" class="modal-title"></h4>
      </div>
      <?php
      $fimIndice = 2;
      if(count($this->pontes) == 0){
        $fimIndice = 1;
      }
      for($indice = 1;$indice <= $fimIndice; $indice++){
        if($indice === 1){
          $formulario = $this->formularioPonte;
          $nomeFormulario = 'Ponte';
        }
        if($indice === 2){
          $formulario = $this->formularioProspecto;
          $nomeFormulario = 'Prospecto';
        }
        echo '<div id="divFormulario'.$nomeFormulario.'">';
        $formulario->prepare();
        $formulario->setAttribute(KleoForm::stringAction, 'admPonteProspectoFinalizar');
        echo $this->form()->openTag($formulario);
        echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
        echo $this->formHidden($formulario->get(KleoForm::inputGrupoPessoaTipo));
        echo '<div class="modal-body">';
        if($indice === 2){
          echo $this->inputFormulario(KleoForm::traducaoPonte, $formulario->get(KleoForm::inputPonte)); 
        }
        echo $this->inputFormulario(KleoForm::traducaoNome, $formulario->get(KleoForm::inputNome.$nomeFormulario)); 
        echo $this->inputFormulario(KleoForm::traducaoTelefone, $formulario->get(KleoForm::inputTelefone.$nomeFormulario)); 
        echo '</div>';
        echo '<div class="modal-footer text-left">';
        echo $this->botao('Cadastrar', $this->funcaoOnClick('submeterFormulario(this.form)')); 
        echo $this->botao('Cancelar', 'data-dismiss="modal"',Botao::botaoSecundario); 
        echo '</div>';
        echo $this->form()->closeTag();
        echo '</div>';
      }
      ?>
    </div>
  </div>
</div>
