<div class="row">


  <div class="col-md-6">
    <!-- Card -->
    <div class="card card-block p-30 bg-blue-600">
      <div class="card-watermark darker font-size-80 m-15"><i class="icon wb-clipboard" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-group">
          <span class="counter-number"><?php echo $this->relatorio[0]['ligacao']; ?></span>
          <span class="counter-number-related text-capitalize">Ligações</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

  <div class="col-md-6">
    <!-- Card -->
    <div class="card card-block p-30 bg-red-600">
      <div class="card-watermark darker font-size-80 m-15"><i class="icon wb-users" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-group">
          <span class="counter-number"><?php echo $this->relatorio[0]['mensagem']; ?></span>
          <span class="counter-number-related text-capitalize">Mensagens</span>
        </div>      </div>
    </div>
    <!-- End Card -->
  </div>
</div>
<div class="row">

  <div class="col-md-6">
    <!-- Card -->
    <div class="card card-block p-30 bg-green-600">
      <div class="card-watermark darker font-size-60 m-15"><i class="icon wb-musical" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-group">
          <span class="counter-number"><?php echo $this->relatorio[0]['ponte']; ?></span>
          <span class="counter-number-related text-capitalize">Pontes</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

  <div class="col-md-6">
    <!-- Card  -->
    <div class="card card-block p-30 bg-purple-600">
      <div class="card-watermark lighter font-size-60 m-15"><i class="icon wb-image" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-wrap font-size-30">
          <span class="counter-number"><?php echo $this->relatorio[0]['prospecto']; ?></span>
          <span class="counter-number-related text-capitalize">Prospecto</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

</div>

<div class="row">

  <div class="col-md-6">
    <!-- Card -->
    <div class="card card-block p-30 bg-blue-600">
      <div class="card-watermark darker font-size-60 m-15"><i class="icon wb-musical" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-group">
          <span class="counter-number"><?php echo $this->relatorio[0]['clique_ligacao']; ?></span>
          <span class="counter-number-related text-capitalize">Clique Ligações</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

  <div class="col-md-6">
    <!-- Card  -->
    <div class="card card-block p-30 bg-red-600">
      <div class="card-watermark lighter font-size-60 m-15"><i class="icon wb-image" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-wrap font-size-30">
          <span class="counter-number"><?php echo $this->relatorio[0]['clique_mensagem']; ?></span>
          <span class="counter-number-related text-capitalize">Clique Mensagens</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

</div>


<div class="row">

  <div class="col-md-6">
    <!-- Card -->
    <div class="card card-block p-30 bg-green-600">
      <div class="card-watermark darker font-size-60 m-15"><i class="icon wb-musical" aria-hidden="true"></i></div>
      <div class="counter counter-md counter-inverse text-left">
        <div class="counter-number-group">
          <span class="counter-number"><?php echo $this->relatorio[0]['frequencia']; ?></span>
          <span class="counter-number-related text-capitalize">Frequências</span>
        </div>
      </div>
    </div>
    <!-- End Card -->
  </div>

</div>