
<?php

use Application\Controller\KleoController;

$html = '';
$html .= '<div class="row">';
for($indice = 1;$indice <= 4; $indice++){
  switch($indice){
    case 1: 
      $label = 'Performance Ponte';
      $performance = $this->relatorio[0][KleoController::relatorioPontePerformance];
      $valor = $this->relatorio[0][KleoController::relatorioPonte];
      $meta = KleoController::metaPonte;
      break;
    case 2: 
      $label = 'Performance Prospecto';
      $performance = $this->relatorio[0][KleoController::relatorioProspectoPerformance];
      $valor = $this->relatorio[0][KleoController::relatorioProspecto];
      $meta = KleoController::metaProspecto;
      break;
    case 3: 
      $label = 'Performance Ligacao';
      $performance = $this->relatorio[0][KleoController::relatorioLigacaoPerformance];
      $valor = $this->relatorio[0][KleoController::relatorioLigacao];
      $meta = KleoController::metaProspecto;
      break;
    case 4: 
      $label = 'Performance Mensagem';
      $performance = $this->relatorio[0][KleoController::relatorioMensagemPerformance];
      $valor = $this->relatorio[0][KleoController::relatorioMensagem];
      $meta = KleoController::metaProspecto;
      break;
  }
  $html .= '<div class="col-xl-3 col-lg-6">';
  $html .= '<div class="card card-block p-30">';
  $html .= '<div class="counter counter-lg">';
  $html .= '<div class="counter-label text-uppercase">'.$label.'</div>';
  $html .= '<div class="counter-number-group">';
  $html .= '<span class="counter-icon mr-10 green-600">';
  $html .= '<i class="wb-stats-bars"></i>';
  $html .= '</span>';
  $html .= '<span class="counter-number">'.$performance.'</span>';
  $html .= '<span class="counter-number-related">%</span>';
  $html .= '<div class="counter-label font-size-16">'.$valor.' de '.$meta.'</div>';
  $html .= '</div>';
  $html .= '</div>';
  $html .= '</div>';
  $html .= '</div>';
}

$html .= '</div>';
?>
<div class="panel">
  <div class="panel-heading">
    <h2 class="panel-title bg-blue-600 white">
      <?php 
      echo KleoController::diaDaSemanaPorDia(date('N'),1).'<br />';
      echo KleoController::mesPorExtenso(date('m'),1).' '. date('d'); ?>
      <p>
        <?php echo $this->cabecalhoDePeriodos('Relatorio'); ?>
      </p>
    </h2>
  </div>
  <div class="panel-body">
    <?php echo $html; ?>
  </div>
</div>