<section id="content" class="pn animated fadeIn">
    <div class="center-block mt50 mw800">
        <h1 class="error-title"> 404! </h1>
        <h2 class="error-subtitle">P&aacute;gina n&atilde;o encontrada.</h2>
    </div>
</section>
<script type="text/javascript">
    window.onload = initPage;
    function initPage() {
        $('body').removeClass('external-page external-alt');
        $('body').addClass('error-page');
    }
</script>