<?php

use Application\Controller\Helper\Constantes;

/** Nome: email-enviado.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página confirmando o email enviado
 */
?>
<?php
/* Layout com top para telas de acesso */
echo $this->layoutLoginTop;
?>
<div class="admin-form theme-info mw500" style="margin-top: 10%;" id="login">
    <div class="row mb15 table-layout">
        <div class="col-xs-12 pln">
            <div class="col-xs-12 text-center">
                <h2 class="text-dark mbn confirmation-header"><i class="fa fa-check text-success"></i></h2>
            </div>
            <div class="col-xs-12 box-separacao"></div>

            <h1 class="titulo-perdeu-sua-senha"><?php echo $this->translate(Constantes::$TRADUCAO_SENHA_ATUALIZADA_COM_SUCESSO); ?></h1>

            <div class="col-xs-12 text-center">
                <?php echo $this->botaoLink(Constantes::$TRADUCAO_ACESSAR, Constantes::$INDEX); ?>
            </div>
        </div>
    </div>
</div>   
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginBotton;
