<?php

use Application\Controller\Helper\Constantes;

/** Nome: esqueceu-senha.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página para recuperação de acesso
 */
$formRecuperarAcesso = $this->formRecuperarAcesso;
$formRecuperarAcesso->prepare();

$classTituloPerdeuSenha = 'titulo-perdeu-sua-senha';
?>
<?php
/* Layout com top para telas de acesso */
echo $this->layoutLoginTop;
?>
<div class="admin-form theme-info mw500" style="margin-top: 10%;" id="login">
    <div class="row mb15 table-layout <?php echo $this->classDiv0; ?>">
        <div class="col-xs-12 pln">
            <div id="opcoes_label">
                <h2 class="<?php echo $classTituloPerdeuSenha ?>"><?php echo $this->translate(Constantes::$TRADUCAO_PERGUNTA_ESQUECI_SENHA); ?></h2>
            </div>
        </div>
    </div>
    <?php
    $tipoNaoEncontrouNaBaseDeDados = 1;
    $tipoMensagemDeSucesso = 1;
    $tipoMensagemDeErro = 2;

    $tipoDaMensagem = $tipoMensagemDeSucesso;
    $mostraMensagem = false;
    if ($this->tipo == $tipoNaoEncontrouNaBaseDeDados) {
        $tipoDaMensagem = 2;
        $mostraMensagem = true;
    }
    /* Div Mensagens */
    echo $this->divMensagens($this->mensagem, $tipoDaMensagem, $mostraMensagem);
    ?>
    <!-- Opções -->
    <div id="opcoes" class="panel mt30 mb25 <?php echo $this->classDiv0; ?>">
        <div class="panel-body bg-light">
            <div class="option-group field section">
                <?php echo $this->formRadio($formRecuperarAcesso->get(Constantes::$INPUT_OPCAO)); ?>
            </div>
        </div>
        <!-- end .form-body section -->
        <div class="panel-footer text-right">
            <?php echo $this->botaoLink(Constantes::$TRADUCAO_CANCELAR, Constantes::$INDEX, 2, ''); ?>
            <?php echo $this->botaoLink(Constantes::$TRADUCAO_CONTINUAR, '#', '', 'id="' . Constantes::$INPUT_BOTAO_CONTINUAR . '" disabled ' . Constantes::$FORM_STRING_ONCLICK . '="abrirOpcao();"'); ?>
        </div>
    </div>
    <?php
    $formRecuperarAcesso->setAttribute('action', $this->url('login', array('action' => 'recuperarAcesso')) . '/1');
    echo $this->form()->openTag($formRecuperarAcesso);
    ?>
    <!-- Opção 1 -->
    <div id="opcao_1" class="panel mt30 mb25 <?php echo $this->classDiv1; ?>">
        <div class="panel-body bg-light"> 
            <p class="text-center"><?php echo $this->translate(Constantes::$TRADUCAO_TITULO_ESQUECI_MINHA_SENHA); ?></p>
            <?php
            /* Username Input */
            echo $this->inputFormularioSimples(Constantes::$TRADUCAO_USUARIO, $formRecuperarAcesso->get(Constantes::$INPUT_USUARIO));
            ?>
        </div>
        <div class="panel-footer text-right">
            <?php
            /* Submit */
            $funcaoVerificarUsuario = $this->funcaoOnClick('validarUsuario(this.form)');
            echo $this->botaoSimples(Constantes::$TRADUCAO_ENVIAR_EMAIL, $funcaoVerificarUsuario);
            echo $this->botaoLink(Constantes::$TRADUCAO_CANCELAR, Constantes::$INDEX, 2, Constantes::$FORM_STRING_ONCLICK . '="abrirOpcao(0);"');
            ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <?php
    $formRecuperarAcesso->setAttribute('action', $this->url('login', array('action' => 'recuperarAcesso')) . '/2');
    echo $this->form()->openTag($formRecuperarAcesso);
    ?>
    <!-- Opção 2 -->
    <div id="opcao_2" class="panel mt30 mb25 <?php echo $this->classDiv2; ?>">
        <div class="panel-body bg-light">
            <div class="section mn">
                <div class="smart-widget">
                    <p class="text-center"><?php echo $this->translate(Constantes::$TRADUCAO_INFORME_2_DIGITO_CPF_DATA_NASCIMENTO); ?></p>
                    <div class="input-group">
                        <span class="input-group-addon">XXX.XXX.XXX-</span>
                        <?php echo $this->formInput($formRecuperarAcesso->get(Constantes::$INPUT_CPF)); ?>                       
                    </div>
                </div>
                <!-- end .smart-widget section -->
                <br />
                <?php
                echo '<div class="row">';
                echo '<div class="col-xs-4">';
                echo $this->formSelect($formRecuperarAcesso->get(Constantes::$FORM_INPUT_DIA));
                echo '</div>';
                echo '<div class="col-xs-4">';
                echo $this->formSelect($formRecuperarAcesso->get(Constantes::$FORM_INPUT_MES));
                echo '</div>';
                echo '<div class="col-xs-4">';
                echo $this->formSelect($formRecuperarAcesso->get(Constantes::$FORM_INPUT_ANO));
                echo '</div>';
                echo '</div>';
                ?>                
            </div>
            <!-- end section -->
        </div>
        <div class="panel-footer text-right">
            <?php echo $this->botaoLink(Constantes::$TRADUCAO_CANCELAR, Constantes::$INDEX, 2, Constantes::$FORM_STRING_ONCLICK . '="abrirOpcao(0);"'); ?>
            <?php
            /* Submit */
            $funcaoVerificarCPFEDataDeNascimento = $this->funcaoOnClick('validarCPFEDataNascimento(this.form)');
            echo $this->botaoSimples(Constantes::$TRADUCAO_VERIFICAR_USUARIO, $funcaoVerificarCPFEDataDeNascimento);
            ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div> 
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginBotton;
?>
<?php
/* Layout com javascript para telas de recuperação de acessos */
echo $this->layoutJSRecuperarAcesso;
