<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: pre-saida.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com>
 * Descricao: Página pré saída
 */
?>
<!-- Start: Main -->
<div id="main-photo" class="animated fadeIn">
    <!-- Start: Header -->
    <header class="navbar-fixed-top barra-transparente">
        <a href="<?php echo Constantes::$INDEX; ?>">
            <img src="<?php echo Constantes::$IMAGEM_LOGO; ?>" title="<?php echo $this->translate(Constantes::$TRADUCAO_NOME_APLICACAO) ?>" class="img-responsive" style="max-width: 275px;">
        </a>
    </header>
    <!-- End: Header -->
    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">
        <!-- Begin: Content -->
        <section id="content">
            <div class="center-block mt70" style="max-width: 625px">

                <!-- Login Logo + Meta -->
                <div class="row table-layout">
                    <div class="col-xs-12 pln">
                        <h2 class="mbn confirmation-header"><?php echo $this->translate(Constantes::$TRADUCAO_SESSAO_ENCERRADA); ?></h2>
                    </div>
                </div>

                <!-- Confirmation Panel -->
                <div class="panel mt15">
                    <div class="panel-body pt30 p25 pb15">

                        <p class="lead"><?php echo $this->translate(Constantes::$TRADUCAO_OLA); ?>&nbsp;<?php echo $this->nome ?>,</p>

                        <hr class="alt short mv25">

                        <p class="lh25 text-muted fs15"><?php echo $this->translate(Constantes::$TRADUCAO_PRE_SAIDA); ?></p>

                        <p class="text-right mt20 col-md-12">
                            <?php echo $this->botaoLink(Constantes::$TRADUCAO_ENTRAR_NOVAMENTE, ($this->url(Constantes::$ROUTE_LOGIN) . Constantes::$URL_PRINCIPAL), 2); ?>
                            <?php echo $this->botaoLink(Constantes::$TRADUCAO_CONTINUAR, ($this->url(Constantes::$ROUTE_LOGIN) . Constantes::$URL_SAIR)); ?>
                        </p>

                    </div>
                </div>

            </div>

        </section>
        <!-- End: Content -->
    </section>
    <!-- End: Content-Wrapper -->
</div>

<!-- End: Main -->
<?php
/* Layout com javascript para tela de index */
echo $this->layoutJSPreSaida;
