<?php

use Application\Controller\Helper\Constantes;

/** Nome: recuperar-senha.phtml
 * @author Leonardo Pereira Magalhães <falecomleonardopereira@gmail.com> e Sergio Bezerra da Silva <sergio.silva.unb@gmail.com>
 * Descricao: Página para redefinição de senha
 */
$formRecuperarSenha = $this->formRecuperarSenha;
$formRecuperarSenha->prepare();
$formRecuperarSenha->setAttribute(Constantes::$ACTION, $this->url(Constantes::$ROUTE_LOGIN, array(Constantes::$ACTION => Constantes::$ACTION_ALTERAR_SENHA)));

echo $this->form()->openTag($formRecuperarSenha);
?>
<?php
/* Layout com top para telas de acesso */
echo $this->layoutLoginTop;
?>
<div class="panel-body bg-light p25 pb15">
    <?php
    echo $this->divMensagens();
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_SENHA, $formRecuperarSenha->get(Constantes::$INPUT_SENHA));
    echo $this->inputFormularioSimples(Constantes::$TRADUCAO_REPITA_A_SENHA, $formRecuperarSenha->get(Constantes::$INPUT_REPETIR_SENHA));
    
    echo $this->formHidden($formRecuperarSenha->get(Constantes::$INPUT_CSRF));
    echo $this->formHidden($formRecuperarSenha->get(Constantes::$INPUT_ID_PESSOA));
    $funcaoValidarSenha = $this->funcaoOnClick('validarSenhas(this.form)');
    echo $this->botaoSimples(Constantes::$TRADUCAO_ALTERAR, $funcaoValidarSenha);
    ?>
</div> 
<?php
/* Layout com botton para telas de acesso */
echo $this->layoutLoginBotton;

/* Layout com javascript para telas de recuperação de acessos */
echo $this->layoutJSRecuperarAcesso;
