<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: atendimento.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
 * Descricao: Página para mostrar eficiência em atendimentos e a quantidade que cada disicpulo foi atendido.
 */
?>
<div class="mw1000 center-block">
    <div class="panel">      
        <?php echo $this->abasPanel(Constantes::$ROUTE_RELATORIO, 'Atendimento'); ?>
        <div class="panel-body center-block">
            <?php echo $this->atendimentoGruposAbaixo(2); ?>  
        </div>
    </div>
</div>