<?php

use Application\Controller\KleoController;

echo $this->doctype();
$versao = '?v=1.2.5';
?>
<html class="no-js css-menubar" lang="pt-BR">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<!-- Title Head -->
		<?php
		$NAME_APPLICATION = $this->translate(KleoController::nomeAplicacao);
		echo $this
			->headTitle($NAME_APPLICATION)
			->setSeparator(' - ')
			->setAutoEscape(false)
			;
		?>
		<!-- Meta Head -->
		<?php
		echo $this
			->headMeta()
			->appendName('keywords', '')
			->appendName('author', KleoController::nomeAplicacao)
			->appendName('description', $NAME_APPLICATION)
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
			;
		?>
		<!-- Styles -->
		<?php
		echo $this
			->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpeg'))               
			->prependStylesheet($this->basePath() . '/global/fonts/brand-icons/brand-icons.min.css')
			->prependStylesheet($this->basePath() . '/global/fonts/web-icons/web-icons.min.css')
			->prependStylesheet($this->basePath() . '/global/vendor/flag-icon-css/flag-icon.css')
			->prependStylesheet($this->basePath() . '/global/vendor/slidepanel/slidePanel.css')
			->prependStylesheet($this->basePath() . '/global/vendor/switchery/switchery.css')
			->prependStylesheet($this->basePath() . '/global/vendor/asscrollable/asScrollable.css')
			->prependStylesheet($this->basePath() . '/global/vendor/animsition/animsition.css')
			->prependStylesheet($this->basePath() . '/assets/css/site.min.css')
			->prependStylesheet($this->basePath() . '/global/css/bootstrap-extend.min.css')
			->prependStylesheet($this->basePath() . '/global/css/bootstrap.min.css')
			->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic')
			;
		echo $this
			->headScript()
			->prependFile($this->basePath() . '/global/vendor/breakpoints/breakpoints.js')
			;
		?>
		<script>
			Breakpoints();
		</script>   
		<!--[if lt IE 9]>
<script src="../../global/vendor/html5shiv/html5shiv.min.js"></script>
<![endif]-->

		<!--[if lt IE 10]>
<script src="../../global/vendor/media-match/media.match.min.js"></script>
<script src="../../global/vendor/respond/respond.min.js"></script>
<![endif]-->
	</head>
	<body class="">
		<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-expand-md" role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
        data-toggle="menubar">
        <span class="sr-only">Toggle navigation</span>
        <span class="hamburger-bar"></span>
      </button>
      <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
        data-toggle="collapse">
        <i class="icon wb-more-horizontal" aria-hidden="true"></i>
      </button>
      <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
        <img class="navbar-brand-logo" src="../../assets/images/logo.png" title="Remark">
        <span class="navbar-brand-text hidden-xs-down"> Remark</span>
      </div>
    </div>

    <div class="navbar-container container-fluid">
      <!-- Navbar Collapse -->
      <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
        <!-- Navbar Toolbar -->
        <ul class="nav navbar-toolbar">
          <li class="nav-item hidden-float" id="toggleMenubar">
            <a class="nav-link" data-toggle="menubar" href="#" role="button">
                <i class="icon hamburger hamburger-arrow-left">
                  <span class="sr-only">Toggle menubar</span>
                  <span class="hamburger-bar"></span>
                </i>
              </a>
          </li>
          <li class="nav-item hidden-sm-down" id="toggleFullscreen">
            <a class="nav-link icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
              <span class="sr-only">Toggle fullscreen</span>
            </a>
          </li>
        </ul>
        <!-- End Navbar Toolbar -->

        <!-- Navbar Toolbar Right -->
        <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
          
          <li class="nav-item dropdown">
            <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"
              data-animation="scale-up" role="button">
              <span class="avatar avatar-online">
                <img src="../../../global/portraits/5.jpg" alt="...">
                <i></i>
              </span>
            </a>
            <div class="dropdown-menu" role="menu">
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-user" aria-hidden="true"></i> Profile</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-payment" aria-hidden="true"></i> Billing</a>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-settings" aria-hidden="true"></i> Settings</a>
              <div class="dropdown-divider" role="presentation"></div>
              <a class="dropdown-item" href="javascript:void(0)" role="menuitem"><i class="icon wb-power" aria-hidden="true"></i> Logout</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" title="Notifications"
              aria-expanded="false" data-animation="scale-up" role="button">
                <i class="icon wb-bell" aria-hidden="true"></i>
                <span class="badge badge-pill badge-danger up">5</span>
              </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
              <div class="dropdown-menu-header">
                <h5>NOTIFICATIONS</h5>
                <span class="badge badge-round badge-danger">New 5</span>
              </div>

              <div class="list-group">
                <div data-role="container">
                  <div data-role="content">
                    <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <i class="icon wb-order bg-red-600 white icon-circle" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">A new order has been placed</h6>
                          <time class="media-meta" datetime="2018-06-12T20:50:48+08:00">5 hours ago</time>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <i class="icon wb-user bg-green-600 white icon-circle" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Completed the task</h6>
                          <time class="media-meta" datetime="2018-06-11T18:29:20+08:00">2 days ago</time>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <i class="icon wb-settings bg-red-600 white icon-circle" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Settings updated</h6>
                          <time class="media-meta" datetime="2018-06-11T14:05:00+08:00">2 days ago</time>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <i class="icon wb-calendar bg-blue-600 white icon-circle" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Event started</h6>
                          <time class="media-meta" datetime="2018-06-10T13:50:18+08:00">3 days ago</time>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item dropdown-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <i class="icon wb-chat bg-orange-600 white icon-circle" aria-hidden="true"></i>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Message received</h6>
                          <time class="media-meta" datetime="2018-06-10T12:34:48+08:00">3 days ago</time>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="dropdown-menu-footer">
                <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                    <i class="icon wb-settings" aria-hidden="true"></i>
                  </a>
                <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
                    All notifications
                  </a>
              </div>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="javascript:void(0)" title="Messages"
              aria-expanded="false" data-animation="scale-up" role="button">
                <i class="icon wb-envelope" aria-hidden="true"></i>
                <span class="badge badge-pill badge-info up">3</span>
              </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
              <div class="dropdown-menu-header" role="presentation">
                <h5>MESSAGES</h5>
                <span class="badge badge-round badge-info">New 3</span>
              </div>

              <div class="list-group" role="presentation">
                <div data-role="container">
                  <div data-role="content">
                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <span class="avatar avatar-sm avatar-online">
                            <img src="../../../global/portraits/2.jpg" alt="..." />
                            <i></i>
                          </span>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Mary Adams</h6>
                          <div class="media-meta">
                            <time datetime="2018-06-17T20:22:05+08:00">30 minutes ago</time>
                          </div>
                          <div class="media-detail">Anyways, i would like just do it</div>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <span class="avatar avatar-sm avatar-off">
                            <img src="../../../global/portraits/3.jpg" alt="..." />
                            <i></i>
                          </span>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Caleb Richards</h6>
                          <div class="media-meta">
                            <time datetime="2018-06-17T12:30:30+08:00">12 hours ago</time>
                          </div>
                          <div class="media-detail">I checheck the document. But there seems</div>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <span class="avatar avatar-sm avatar-busy">
                            <img src="../../../global/portraits/4.jpg" alt="..." />
                            <i></i>
                          </span>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">June Lane</h6>
                          <div class="media-meta">
                            <time datetime="2018-06-16T18:38:40+08:00">2 days ago</time>
                          </div>
                          <div class="media-detail">Lorem ipsum Id consectetur et minim</div>
                        </div>
                      </div>
                    </a>
                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                      <div class="media">
                        <div class="pr-10">
                          <span class="avatar avatar-sm avatar-away">
                            <img src="../../../global/portraits/5.jpg" alt="..." />
                            <i></i>
                          </span>
                        </div>
                        <div class="media-body">
                          <h6 class="media-heading">Edward Fletcher</h6>
                          <div class="media-meta">
                            <time datetime="2018-06-15T20:34:48+08:00">3 days ago</time>
                          </div>
                          <div class="media-detail">Dolor et irure cupidatat commodo nostrud nostrud.</div>
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
              <div class="dropdown-menu-footer" role="presentation">
                <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                    <i class="icon wb-settings" aria-hidden="true"></i>
                  </a>
                <a class="dropdown-item" href="javascript:void(0)" role="menuitem">
                    See all messages
                  </a>
              </div>
            </div>
          </li>
        </ul>
        <!-- End Navbar Toolbar Right -->
      </div>
      <!-- End Navbar Collapse -->

    </div>
		
</nav>

		<!-- Page -->
		<div class="page">
			<div class="page-content container-fluid">
				<?php
				echo $this->content;
				?>      
			</div>
		</div>
		<!-- End Page -->
		<!-- Footer -->
		<footer class="site-footer">
			<div class="site-footer-legal">© 2018 <a href="http://themeforest.net/item/remark-responsive-bootstrap-admin-template/11989202">Remark</a></div>
			<div class="site-footer-right">
				Crafted with <i class="red-600 wb wb-heart"></i> by <a href="https://themeforest.net/user/creation-studio">Creation Studio</a>
			</div>
		</footer>
		<!-- BEGIN: PAGE SCRIPTS -->
		<?php
		echo $this
			->headScript()
			->prependFile($this->basePath() . '/js/validacoes.js' . $versao)
			->prependFile($this->basePath() . '/js/funcoes.js' . $versao)
			->prependFile($this->basePath() . '/assets/js/config/tour.js')
			->prependFile($this->basePath() . '/global/js/config/colors.js')
			->prependFile($this->basePath() . '/assets/js/Plugin/menu.js')
			->prependFile($this->basePath() . '/assets/js/Section/PageAside.js')
			->prependFile($this->basePath() . '/assets/js/Section/Sidebar.js')
			->prependFile($this->basePath() . '/assets/js/Section/GridMenu.js')
			->prependFile($this->basePath() . '/assets/js/Section/Menubar.js')
			->prependFile($this->basePath() . '/global/js/Config.js')
			->prependFile($this->basePath() . '/global/js/Plugin.js')
			->prependFile($this->basePath() . '/global/js/Base.js')
			->prependFile($this->basePath() . '/global/js/Component.js')
			->prependFile($this->basePath() . '/global/vendor/ashoverscroll/jquery-asHoverScroll.js')
			->prependFile($this->basePath() . '/global/vendor/asscrollable/jquery-asScrollable.js')
			->prependFile($this->basePath() . '/global/vendor/asscrollbar/jquery-asScrollbar.js')
			->prependFile($this->basePath() . '/global/vendor/mousewheel/jquery.mousewheel.js')
			->prependFile($this->basePath() . '/global/vendor/animsition/animsition.js')
			->prependFile($this->basePath() . '/global/vendor/bootstrap/bootstrap.js')
			->prependFile($this->basePath() . '/global/vendor/popper-js/umd/popper.min.js')
			->prependFile($this->basePath() . '/global/vendor/jquery/jquery.js')
			->prependFile($this->basePath() . '/global/vendor/babel-external-helpers/babel-external-helpers.js')
			;
		echo $this->inlineScript();
		?>
		<script>Config.set('assets', '../../../assets');</script>

		<script type="text/javascript">

		</script>
		<!-- END: PAGE SCRIPTS -->
	</body>
</html>
