<?php

use Application\Controller\KleoController;

echo $this->doctype();
$versao = '?v=2.9';
?>
<html class="no-js css-menubar" lang="pt-BR">
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<!-- Title Head -->
		<?php
		$NAME_APPLICATION = $this->translate(KleoController::nomeAplicacaoFormatado);
		echo $this
			->headTitle($NAME_APPLICATION)
			->setSeparator(' - ')
			->setAutoEscape(false)
			;
		?>
		<!-- Meta Head -->
		<?php
		echo $this
			->headMeta()
			->appendName('keywords', '')
			->appendName('author', KleoController::nomeAplicacao)
			->appendName('description', $NAME_APPLICATION)
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
			;
		?>
		<!-- Styles -->
		<?php
		echo $this
			->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.jpeg'))               
			->prependStylesheet($this->basePath() . '/css/splash.css' . $versao)			
			->prependStylesheet($this->basePath() . '/global/vendor/ladda/ladda.min.css')
			->prependStylesheet($this->basePath() . '/global/fonts/web-icons/web-icons.min.css')
			->prependStylesheet($this->basePath() . '/global/fonts/font-awesome/font-awesome.min.css')
			->prependStylesheet($this->basePath() . '/global/vendor/slidepanel/slidePanel.css')
			->prependStylesheet($this->basePath() . '/global/vendor/switchery/switchery.css')
			->prependStylesheet($this->basePath() . '/global/vendor/asscrollable/asScrollable.css')
			->prependStylesheet($this->basePath() . '/global/vendor/animsition/animsition.css')
			->prependStylesheet($this->basePath() . '/assets/css/site.min.css')
			->prependStylesheet($this->basePath() . '/global/css/bootstrap-extend.min.css')
			->prependStylesheet($this->basePath() . '/global/css/bootstrap.min.css')
			->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic')
			;
		echo $this
			->headScript()
			->prependFile($this->basePath() . '/global/vendor/breakpoints/breakpoints.js')
			;
		?>
		<script>
			Breakpoints();
		</script>   
		<!--[if lt IE 9]>
<script src="../../global/vendor/html5shiv/html5shiv.min.js"></script>
<![endif]-->

		<!--[if lt IE 10]>
<script src="../../global/vendor/media-match/media.match.min.js"></script>
<script src="../../global/vendor/respond/respond.min.js"></script>
<![endif]-->
	</head>
	<body class="">
		<?php echo $this->splash(); ?>
		<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
		<?php
		$uri = $_SERVER['REQUEST_URI'];
		if ($this->mostrarMenu !== 0 && 
				$uri != '/' &&
				$uri != '/login') {
			echo $this->menu();
		}
		?> 
		<!-- Page -->
		<div class="page">
			<div class="page-content container-fluid">
				<?php
				echo $this->content;
				?>
			</div>
		</div>
		<!-- End Page -->
		<!-- Footer -->
		<footer class="site-footer">
			<div class="site-footer-legal">© 2018 <?php echo KleoController::nomeAFabrica; ?></div>
		</footer>
		<!-- BEGIN: PAGE SCRIPTS -->
		<?php
		echo $this
			->headScript()
			->prependFile($this->basePath() . '/js/validacoes.js' . $versao)
			->prependFile($this->basePath() . '/js/funcoes.js' . $versao)			
			->prependFile($this->basePath() . '/global/vendor/ladda/ladda.min.js')
			->prependFile($this->basePath() . '/global/vendor/ladda/spin.min.js')
			->prependFile($this->basePath() . '/assets/js/config/tour.js')
			->prependFile($this->basePath() . '/global/js/config/colors.js')
			->prependFile($this->basePath() . '/assets/js/Plugin/menu.js')
			->prependFile($this->basePath() . '/assets/js/Section/PageAside.js')
			->prependFile($this->basePath() . '/assets/js/Section/Sidebar.js')
			->prependFile($this->basePath() . '/assets/js/Section/GridMenu.js')
			->prependFile($this->basePath() . '/assets/js/Section/Menubar.js')
			->prependFile($this->basePath() . '/global/js/Config.js')
			->prependFile($this->basePath() . '/global/js/Plugin.js')
			->prependFile($this->basePath() . '/global/js/Base.js')
			->prependFile($this->basePath() . '/global/js/Component.js')
			->prependFile($this->basePath() . '/global/vendor/ashoverscroll/jquery-asHoverScroll.js')
			->prependFile($this->basePath() . '/global/vendor/asscrollable/jquery-asScrollable.js')
			->prependFile($this->basePath() . '/global/vendor/asscrollbar/jquery-asScrollbar.js')
			->prependFile($this->basePath() . '/global/vendor/mousewheel/jquery.mousewheel.js')
			->prependFile($this->basePath() . '/global/vendor/animsition/animsition.js')
			->prependFile($this->basePath() . '/global/vendor/bootstrap/bootstrap.js')
			->prependFile($this->basePath() . '/global/vendor/popper-js/umd/popper.min.js')
			->prependFile($this->basePath() . '/global/vendor/jquery/jquery.js')
			->prependFile($this->basePath() . '/global/vendor/babel-external-helpers/babel-external-helpers.js')
			;
		echo $this->inlineScript();
		?>
		<script>Config.set('assets', '../../../assets');</script>

		<script type="text/javascript">
			jQuery(document).ready(function () {
				"use strict";

				// Init Ladda Plugin on buttons
				Ladda.bind('.ladda-button', {
					timeout: 1000
				});					
			});
		</script>
		<!-- END: PAGE SCRIPTS -->
	</body>
</html>
