<!-- Start: Main -->
<div id="main" class="animated fadeIn center-block">

    <!-- Start: Content-Wrapper -->
    <section id="content_wrapper">

        <!-- Begin: Content -->
        <section id="content">

            <div class="admin-form theme-info mw500" id="login">

                <!-- Login Logo -->
                <div class="row table-layout">
                    <?php
                    /* Logo com link para index */
                    echo $this->linkLogo();
                    ?>
                </div>