<?php

use Application\Controller\Helper\Constantes;

/**
 * Nome: atendimento.phtml
 * @author Lucas Filipe de Carvalho Cunha <lucascarvalho.esw@gmail.com>
 * Descricao: Página para mostrar eficiência em atendimentos e a quantidade que cada disicpulo foi atendido.
 */
?>
<div class="mw1000 center-block">
    <div class="panel">      
        <?php echo $this->abasPanel(Constantes::$ROUTE_LANCAMENTO, 'Atendimento'); ?>
        <div class="panel-body center-block">
            <div class="row center-block text-center">
                <?php echo $this->cabecalhoDeAtendimentos($this->gruposAbaixo); ?>     
            </div>
            <?php echo $this->atendimentoGruposAbaixo(); ?>        
        </div>
    </div>
</div>
