<?php

use Application\Controller\KleoController;
?>
<style type="text/css">
  .page-maintenance-icon.icon {
    font-size:64px
  }
</style>

<div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">>
  <div class="page-content vertical-align-middle">
    <i class="icon wb-settings icon-spin page-maintenance-icon" aria-hidden="true"></i>
    <h2>Em Produção</h2>
    <p><a class="btn btn-primary" href="/login">Acesso <?php echo KleoController::nomeAplicacaoFormatado; ?></a></p>
    <footer class="page-copyright">
      <p><?php echo KleoController::nomeAFabrica; ?></p>
      <p>© 2018. All RIGHT RESERVED.</p>     
    </footer>
  </div>
</div>