<?php

use Application\Form\KleoForm;

$formulario = $this->formulario;
$formulario->prepare();

$formulario->setAttribute(KleoForm::stringAction, 'logar');
echo $this->form()->openTag($formulario);
echo $this->formHidden($formulario->get(KleoForm::inputCSRF));
?>
<div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">>
  <div class="page-content vertical-align-middle animation-slide-top animation-duration-1">
    <div class="brand">
      <img class="brand-img" src="../assets/images/logo.png" alt="...">
      <h2 class="brand-text">Remark</h2>
    </div>
    <p>Sign into your pages account</p>
    <form method="post" action="login.html">
      <div class="form-group">
        <label class="sr-only" for="inputEmail">Email</label>
        <input type="email" class="form-control" id="inputEmail" name="email" placeholder="Email">
      </div>
      <?php
      if ($this->error) {
        echo '<p class="alert alert-danger">' . $this->error . '</p>';
      }
      echo $this->inputFormulario(KleoForm::traducaoEmail, $formulario->get(KleoForm::inputEmail));
      ?>  
      <?php echo $this->inputFormulario(KleoForm::traducaoSenha, $formulario->get(KleoForm::inputSenha)); ?>

      <div class="form-group">
        <label class="sr-only" for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" name="password"
               placeholder="Password">
      </div>
      <div class="form-group clearfix">
        <div class="checkbox-custom checkbox-inline checkbox-primary float-left">
          <input type="checkbox" id="inputCheckbox" name="remember">
          <label for="inputCheckbox">Remember me</label>
        </div>
        <a class="float-right" href="forgot-password.html">Forgot password?</a>
      </div>
      <?php echo $this->botao('Entrar', $this->funcaoOnClickSubmeterFormulario()); ?>

      <button type="submit" class="btn btn-primary btn-block">Sign in</button>
    </form>
    <p>Still no account? Please go to <a href="register.html">Register</a></p>


  </div>
</div>
<?php
echo $this->form()->closeTag();
